# Generated by Django 3.2.4 on 2021-06-26 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('anio', models.DateTimeField(auto_now=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('cliente_nombre', models.CharField(max_length=50)),
                ('cliente_direccion', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='LineaFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=300)),
                ('precio_unitario', models.FloatField(default=0)),
                ('unidades', models.IntegerField(default=1)),
                ('propietario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='factura.factura')),
            ],
        ),
    ]
