# Generated by Django 3.2.4 on 2021-06-26 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_lineafactura_iva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='anio',
        ),
    ]
